apiVersion: v1
kind: Service
metadata:
  name: nordbye-service-stage
  namespace: stage-portfolio 
spec:
  selector:
    app: stage-portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
