apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-portfolio
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-portfolio
  source:
    repoURL: 'https://gitlab.bigd.no/homelab/k8s/k3sa/app-config/portfolio.git'
    targetRevision: main
    path: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: "5s"
        factor: 2
        maxDuration: "3m"
